# source("http://bioconductor.org/biocLite.R")
# biocLite("RBGL")
install.packages('BiocManager')
BiocManager::install(c("RBGL"))
install.packages('pcalg')
install.packages('InvariantCausalPrediction')
install.packages('RcppCNPy')
